-- Supabase Schema Migration for Maple Rental (Safe)

-- UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- NOTE:
-- This migration is intentionally non-destructive.
-- For local/dev resets, run explicit DROP statements in a separate reset script.

-- 1. Cars Table
CREATE TABLE cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  model_year INTEGER NOT NULL,
  weekly_price NUMERIC NOT NULL CHECK (weekly_price >= 0),
  bond NUMERIC NOT NULL CHECK (bond >= 0),
  status TEXT NOT NULL DEFAULT 'Available',
  image TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Applications Table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE, -- Prevent duplicate applications
  license_number TEXT NOT NULL,
  license_expiry DATE NOT NULL, -- Proper DATE type
  uber_status TEXT NOT NULL,
  experience TEXT NOT NULL,
  address TEXT NOT NULL,
  weekly_budget TEXT,
  intended_start_date DATE NOT NULL, -- Proper DATE type
  license_photo TEXT,
  uber_screenshot TEXT,
  status TEXT DEFAULT 'Pending' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. Rentals Table
CREATE TABLE rentals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE,
  weekly_price NUMERIC NOT NULL CHECK (weekly_price >= 0),
  bond_paid NUMERIC DEFAULT 0 NOT NULL,
  status TEXT DEFAULT 'Active' NOT NULL,
  stripe_subscription_id TEXT,
  stripe_customer_id TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 4. Bookings Table
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  application_id BIGINT REFERENCES applications(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
  status TEXT DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 5. Merchants Table (SaaS)
CREATE TABLE merchants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  country TEXT NOT NULL,
  stripe_account_id TEXT NOT NULL UNIQUE,
  payout_interval TEXT NOT NULL,
  onboarding_status TEXT DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 6. Lease Agreements Table
CREATE TABLE lease_agreements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'generated' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 7. Admins Table (Single-Admin Whitelist)
CREATE TABLE admins (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Function to check if the current user is an admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM admins WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- --- INDEXES (For Performance) ---
CREATE INDEX idx_rentals_car_id ON rentals(car_id);
CREATE INDEX idx_rentals_application_id ON rentals(application_id);
CREATE INDEX idx_bookings_car_id ON bookings(car_id);
CREATE INDEX idx_bookings_application_id ON bookings(application_id);
CREATE INDEX idx_lease_agreements_application_id ON lease_agreements(application_id);
CREATE INDEX idx_lease_agreements_car_id ON lease_agreements(car_id);

-- --- SECURITY (Row Level Security) ---

-- Enable RLS on all tables
ALTER TABLE cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE rentals ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchants ENABLE ROW LEVEL SECURITY;
ALTER TABLE lease_agreements ENABLE ROW LEVEL SECURITY;

-- Define Admin Policy (Restricts access to the admins table)
CREATE POLICY admin_full_access ON cars FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON applications FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON rentals FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON bookings FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON merchants FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON lease_agreements FOR ALL TO authenticated USING (is_admin());

-- Public Access (Read-only for Cars, Insert for Applications)
CREATE POLICY public_view_cars ON cars FOR SELECT TO anon USING (status = 'Available');
CREATE POLICY public_submit_application ON applications FOR INSERT TO anon WITH CHECK (true);
