CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.admins
    WHERE id = auth.uid()
  );
END;
$$;

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id TEXT,
  staff_number TEXT,
  full_name TEXT NOT NULL,
  preferred_name TEXT,
  company_name TEXT,
  phone TEXT,
  email TEXT,
  date_of_birth DATE,
  street TEXT,
  city TEXT,
  postcode TEXT,
  state TEXT,
  source TEXT NOT NULL DEFAULT 'legacy-import',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_external_id_unique
  ON customers(external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_staff_number_unique
  ON customers(staff_number)
  WHERE staff_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_full_name ON customers(full_name);

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_invoice_number TEXT NOT NULL UNIQUE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  car_registration TEXT,
  invoice_date DATE NOT NULL,
  due_label TEXT,
  amount NUMERIC NOT NULL CHECK (amount >= 0),
  balance NUMERIC NOT NULL CHECK (balance >= 0),
  transaction_summary TEXT,
  source TEXT NOT NULL DEFAULT 'legacy-import',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_car_registration ON invoices(car_registration);
CREATE INDEX IF NOT EXISTS idx_invoices_invoice_date ON invoices(invoice_date);

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'customers'
      AND policyname = 'admin_full_access'
  ) THEN
    CREATE POLICY admin_full_access ON customers
      FOR ALL TO authenticated
      USING (is_admin());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'invoices'
      AND policyname = 'admin_full_access'
  ) THEN
    CREATE POLICY admin_full_access ON invoices
      FOR ALL TO authenticated
      USING (is_admin());
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
