-- Supabase Schema Migration for Maple Rental

-- UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables just in case of partial runs (Optional, but safe for clean slate)
DROP TABLE IF EXISTS merchants CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS rentals CASCADE;
DROP TABLE IF EXISTS applications CASCADE;
DROP TABLE IF EXISTS cars CASCADE;

CREATE TABLE cars (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "modelYear" INTEGER NOT NULL,
  "weeklyPrice" NUMERIC NOT NULL,
  "bond" NUMERIC NOT NULL,
  "status" TEXT NOT NULL,
  "image" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE applications (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "licenseNumber" TEXT NOT NULL,
  "licenseExpiry" TEXT NOT NULL,
  "uberStatus" TEXT NOT NULL,
  "experience" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "weeklyBudget" TEXT,
  "intendedStartDate" TEXT NOT NULL,
  "licensePhoto" TEXT,
  "uberScreenshot" TEXT,
  "status" TEXT DEFAULT 'Pending' NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE rentals (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "carId" BIGINT NOT NULL REFERENCES cars("id") ON DELETE CASCADE,
  "applicationId" BIGINT NOT NULL REFERENCES applications("id") ON DELETE CASCADE,
  "startDate" TEXT NOT NULL,
  "endDate" TEXT,
  "weeklyPrice" NUMERIC NOT NULL,
  "bondPaid" NUMERIC DEFAULT 0 NOT NULL,
  "status" TEXT DEFAULT 'Active' NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE bookings (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "carId" BIGINT NOT NULL REFERENCES cars("id") ON DELETE CASCADE,
  "applicationId" BIGINT REFERENCES applications("id") ON DELETE CASCADE,
  "startDate" TEXT NOT NULL,
  "endDate" TEXT NOT NULL,
  "totalAmount" NUMERIC NOT NULL,
  "status" TEXT DEFAULT 'pending' NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE merchants (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "country" TEXT NOT NULL,
  "stripeAccountId" TEXT NOT NULL UNIQUE,
  "payoutInterval" TEXT NOT NULL,
  "onboardingStatus" TEXT DEFAULT 'pending' NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);
