-- Supabase Schema Migration for Aurora Rentals (Safe)

-- UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- NOTE:
-- This migration is intentionally non-destructive.
-- For local/dev resets, run explicit DROP statements in a separate reset script.

-- 1. Cars Table
CREATE TABLE IF NOT EXISTS cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  model_year INTEGER NOT NULL,
  weekly_price NUMERIC NOT NULL CHECK (weekly_price >= 0),
  bond NUMERIC NOT NULL CHECK (bond >= 0),
  status TEXT NOT NULL DEFAULT 'Available',
  image TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Applications Table
CREATE TABLE IF NOT EXISTS applications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  license_number TEXT NOT NULL,
  license_expiry DATE NOT NULL,
  uber_status TEXT NOT NULL,
  experience TEXT NOT NULL,
  address TEXT NOT NULL,
  weekly_budget TEXT,
  intended_start_date DATE NOT NULL,
  license_photo TEXT,
  license_back_photo TEXT,
  approved_bond NUMERIC CHECK (approved_bond >= 0),
  approved_vehicle TEXT,
  approved_weekly_price NUMERIC CHECK (approved_weekly_price >= 0),
  payment_link_version INTEGER NOT NULL DEFAULT 0,
  payment_link_sent_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  pending_checkout_session_id TEXT,
  status TEXT DEFAULT 'Pending' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. Rentals Table
CREATE TABLE IF NOT EXISTS rentals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  application_id UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE,
  weekly_price NUMERIC NOT NULL CHECK (weekly_price >= 0),
  bond_paid NUMERIC DEFAULT 0 NOT NULL,
  status TEXT DEFAULT 'Active' NOT NULL,
  stripe_subscription_id TEXT,
  stripe_customer_id TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 4. Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  application_id UUID REFERENCES applications(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
  status TEXT DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 5. Lease Agreements Table
CREATE TABLE IF NOT EXISTS lease_agreements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  car_id BIGINT NOT NULL REFERENCES cars(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  status TEXT DEFAULT 'generated' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 7. Customers Table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id TEXT,
  staff_number TEXT,
  full_name TEXT NOT NULL,
  preferred_name TEXT,
  company_name TEXT,
  phone TEXT,
  email TEXT,
  date_of_birth DATE,
  street TEXT,
  city TEXT,
  postcode TEXT,
  state TEXT,
  source TEXT NOT NULL DEFAULT 'legacy-import',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 8. Invoices Table
CREATE TABLE IF NOT EXISTS invoices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  external_invoice_number TEXT NOT NULL UNIQUE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  car_registration TEXT,
  invoice_date DATE NOT NULL,
  due_label TEXT,
  amount NUMERIC NOT NULL CHECK (amount >= 0),
  balance NUMERIC NOT NULL CHECK (balance >= 0),
  transaction_summary TEXT,
  source TEXT NOT NULL DEFAULT 'legacy-import',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS stripe_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'received'
    CHECK (status IN ('received', 'processing', 'processed', 'failed')),
  error_message TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMPTZ
);

-- 9. Admins Table (Single-Admin Whitelist)
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Function to check if the current user is an admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.admins
    WHERE id = auth.uid()
  );
END;
$$;

-- --- INDEXES (For Performance) ---
CREATE INDEX IF NOT EXISTS idx_rentals_car_id ON rentals(car_id);
CREATE INDEX IF NOT EXISTS idx_rentals_application_id ON rentals(application_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_rentals_live_car_unique
  ON rentals(car_id)
  WHERE lower(status) IN ('active', 'overdue');

CREATE UNIQUE INDEX IF NOT EXISTS idx_rentals_live_application_unique
  ON rentals(application_id)
  WHERE lower(status) IN ('active', 'overdue');

CREATE UNIQUE INDEX IF NOT EXISTS idx_rentals_stripe_subscription_unique
  ON rentals(stripe_subscription_id)
  WHERE stripe_subscription_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bookings_car_id ON bookings(car_id);
CREATE INDEX IF NOT EXISTS idx_bookings_application_id ON bookings(application_id);
CREATE INDEX IF NOT EXISTS idx_lease_agreements_application_id ON lease_agreements(application_id);
CREATE INDEX IF NOT EXISTS idx_lease_agreements_car_id ON lease_agreements(car_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_single_active
  ON applications(email)
  WHERE lower(status) IN ('pending', 'approved', 'payment review');

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_external_id_unique
  ON customers(external_id)
  WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_staff_number_unique
  ON customers(staff_number)
  WHERE staff_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_full_name ON customers(full_name);
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_car_registration ON invoices(car_registration);
CREATE INDEX IF NOT EXISTS idx_invoices_invoice_date ON invoices(invoice_date);

CREATE UNIQUE INDEX IF NOT EXISTS idx_stripe_webhook_events_event_id
  ON stripe_webhook_events(stripe_event_id);

CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_processed_at
  ON stripe_webhook_events(processed_at DESC);

CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_status
  ON stripe_webhook_events(status);

CREATE INDEX IF NOT EXISTS idx_applications_email ON applications(email);
CREATE INDEX IF NOT EXISTS idx_applications_phone ON applications(phone);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_applications_created_at ON applications(created_at);
CREATE INDEX IF NOT EXISTS idx_cars_status ON cars(status);
CREATE INDEX IF NOT EXISTS idx_rentals_status ON rentals(status);

-- --- SECURITY (Row Level Security) ---

-- Enable RLS on all tables
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE rentals ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE lease_agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE stripe_webhook_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.admins FROM anon, authenticated;

-- Drop policies first so this migration can safely re-run in Supabase Preview.
DROP POLICY IF EXISTS admin_full_access ON cars;
DROP POLICY IF EXISTS admin_full_access ON applications;
DROP POLICY IF EXISTS admin_full_access ON rentals;
DROP POLICY IF EXISTS admin_full_access ON bookings;
DROP POLICY IF EXISTS admin_full_access ON lease_agreements;
DROP POLICY IF EXISTS admin_full_access ON customers;
DROP POLICY IF EXISTS admin_full_access ON invoices;
DROP POLICY IF EXISTS admin_full_access ON stripe_webhook_events;
DROP POLICY IF EXISTS public_view_cars ON cars;
DROP POLICY IF EXISTS public_submit_application ON applications;

-- Define Admin Policy
CREATE POLICY admin_full_access ON cars FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON applications FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON rentals FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON bookings FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON lease_agreements FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON customers FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON invoices FOR ALL TO authenticated USING (is_admin());
CREATE POLICY admin_full_access ON stripe_webhook_events FOR ALL TO authenticated USING (is_admin());

-- Public Access
CREATE POLICY public_view_cars ON cars FOR SELECT TO anon USING (status = 'Available');
CREATE POLICY public_submit_application ON applications FOR INSERT TO anon WITH CHECK (true);
