-- Restore production compatibility for explicit UUID-native rental activation.
--
-- The UUID conversion retained the former numeric application foreign key as
-- legacy_application_id. Historical/imported rentals keep that value, while
-- rentals created from applications.id must be allowed to leave it NULL.
--
-- rentals.id is GENERATED BY DEFAULT AS IDENTITY. PostgreSQL owns its existing
-- public.rentals_id_seq relationship through identity metadata, so a NULL
-- information_schema.column_default is expected and must not be replaced with
-- SERIAL-style default semantics. No identity configuration or rental id is
-- changed by this migration.
--
-- Compatibility
--   The deployed activation payload intentionally omits id and
--   legacy_application_id. The existing identity generates id; this migration
--   permits the retained legacy field to be NULL. Older writers that explicitly
--   provide legacy_application_id remain compatible.
--
-- Preflight
--   Confirm rentals.id remains GENERATED BY DEFAULT AS IDENTITY, its associated
--   sequence is public.rentals_id_seq, and the next identity value is above
--   max(rentals.id). The DO block is read-only and fails closed on drift.
--
-- Recovery
--   Prefer a forward correction. The nullable-column change is transactional.
--   Do not restore legacy_application_id NOT NULL after UUID-native rentals
--   exist. The identity and sequence require no rollback because they are not
--   mutated here.
--
-- Tests
--   api/rentalActivationMigration.test.ts and api/paymentLifecycle.test.ts.

BEGIN;

SET LOCAL lock_timeout = '10s';

-- Keep the read-only identity preflight and nullable-column change against one
-- stable rental snapshot. Fail fast rather than waiting indefinitely.
LOCK TABLE public.rentals IN ACCESS EXCLUSIVE MODE;

DO $$
DECLARE
  associated_sequence REGCLASS;
  expected_sequence REGCLASS := to_regclass('public.rentals_id_seq');
  highest_rental_id BIGINT;
  rental_id_generation TEXT;
  rental_id_is_identity TEXT;
  sequence_is_called BOOLEAN;
  sequence_last_value BIGINT;
BEGIN
  SELECT column_info.is_identity, column_info.identity_generation
  INTO rental_id_is_identity, rental_id_generation
  FROM information_schema.columns AS column_info
  WHERE column_info.table_schema = 'public'
    AND column_info.table_name = 'rentals'
    AND column_info.column_name = 'id';

  IF rental_id_is_identity IS DISTINCT FROM 'YES' THEN
    RAISE EXCEPTION
      'Cannot relax rentals legacy identity: rentals.id is not an identity column';
  END IF;

  IF rental_id_generation IS DISTINCT FROM 'BY DEFAULT' THEN
    RAISE EXCEPTION
      'Cannot relax rentals legacy identity: rentals.id identity generation is %, expected BY DEFAULT',
      COALESCE(rental_id_generation, 'NULL');
  END IF;

  IF expected_sequence IS NULL THEN
    RAISE EXCEPTION
      'Cannot relax rentals legacy identity: public.rentals_id_seq does not exist';
  END IF;

  SELECT to_regclass(pg_get_serial_sequence('public.rentals', 'id'))
  INTO associated_sequence;

  IF associated_sequence IS DISTINCT FROM expected_sequence THEN
    RAISE EXCEPTION
      'Cannot relax rentals legacy identity: rentals.id uses sequence %, expected public.rentals_id_seq',
      COALESCE(associated_sequence::TEXT, 'NULL');
  END IF;

  SELECT max(id)
  INTO highest_rental_id
  FROM public.rentals;

  SELECT last_value, is_called
  INTO sequence_last_value, sequence_is_called
  FROM public.rentals_id_seq;

  -- When is_called is true, the next identity value is last_value + 1. When it
  -- is false, the next value is last_value. Fail closed if either state could
  -- generate an id that is not strictly above the current maximum.
  IF highest_rental_id IS NOT NULL
     AND (
       (sequence_is_called AND sequence_last_value < highest_rental_id)
       OR (NOT sequence_is_called AND sequence_last_value <= highest_rental_id)
     ) THEN
    RAISE EXCEPTION
      'Cannot relax rentals legacy identity: rentals_id_seq position is not above existing rental ids';
  END IF;
END
$$;

ALTER TABLE public.rentals
  ALTER COLUMN legacy_application_id DROP NOT NULL;

NOTIFY pgrst, 'reload schema';

COMMIT;
