-- Production hardening for immutable agreements, operational auditing,
-- document retention holds, least-privilege Data API access, and FK indexes.
--
-- Backup requirement:
--   Take and verify a logical database backup before applying this migration.
-- Rollback limitations:
--   Agreement mutations rejected after this migration cannot be replayed.
--   Audit events and retention holds created after rollout must be exported
--   before dropping their tables. Restoring broader grants increases risk and
--   should only be done from a reviewed privilege snapshot.

BEGIN;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon;
GRANT USAGE ON SCHEMA private TO authenticated, service_role;

CREATE OR REPLACE FUNCTION private.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.admins
    WHERE lower(email) = lower(COALESCE(auth.jwt() ->> 'email', ''))
  );
$$;

REVOKE ALL ON FUNCTION private.is_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.is_admin() TO authenticated, service_role;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'agreement_templates',
    'applications',
    'bookings',
    'customers',
    'invoices',
    'lease_agreements',
    'maintenance_reset_audit_events',
    'manual_invoice_audit_events',
    'manual_invoice_items',
    'manual_invoices',
    'merchants',
    'rentals',
    'stripe_webhook_events',
    'toll_transfer_notice_audit_events',
    'toll_transfer_notices'
  ]
  LOOP
    IF to_regclass(format('public.%I', table_name)) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
      EXECUTE format('DROP POLICY IF EXISTS admin_full_access ON public.%I', table_name);
      EXECUTE format(
        'CREATE POLICY admin_full_access ON public.%I FOR ALL TO authenticated USING (private.is_admin()) WITH CHECK (private.is_admin())',
        table_name
      );
    END IF;
  END LOOP;
END $$;

-- Abort rather than cascading if an unexpected dependency still uses the
-- exposed helper. All known policies were recreated above.
DROP FUNCTION IF EXISTS public.is_admin();

CREATE TABLE IF NOT EXISTS public.admin_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  actor TEXT,
  target_type TEXT NOT NULL,
  target_id TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_events_created_at
  ON public.admin_audit_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_events_target
  ON public.admin_audit_events (target_type, target_id, created_at DESC);

ALTER TABLE public.admin_audit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.admin_audit_events FROM anon, authenticated;
GRANT SELECT, INSERT ON public.admin_audit_events TO authenticated;
GRANT ALL ON public.admin_audit_events TO service_role;

CREATE POLICY admin_audit_read
  ON public.admin_audit_events FOR SELECT TO authenticated
  USING (private.is_admin());
CREATE POLICY admin_audit_insert
  ON public.admin_audit_events FOR INSERT TO authenticated
  WITH CHECK (private.is_admin());

CREATE TABLE IF NOT EXISTS public.document_retention_holds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id UUID REFERENCES public.applications(id) ON DELETE SET NULL,
  storage_path TEXT NOT NULL UNIQUE,
  reason TEXT NOT NULL,
  held_until TIMESTAMPTZ,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_at TIMESTAMPTZ,
  CONSTRAINT document_retention_holds_reason_not_blank CHECK (btrim(reason) <> '')
);

CREATE INDEX IF NOT EXISTS idx_document_retention_holds_active
  ON public.document_retention_holds (storage_path, held_until)
  WHERE released_at IS NULL;

ALTER TABLE public.document_retention_holds ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.document_retention_holds FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.document_retention_holds TO authenticated;
GRANT ALL ON public.document_retention_holds TO service_role;

CREATE POLICY admin_retention_hold_read
  ON public.document_retention_holds FOR SELECT TO authenticated
  USING (private.is_admin());
CREATE POLICY admin_retention_hold_insert
  ON public.document_retention_holds FOR INSERT TO authenticated
  WITH CHECK (private.is_admin());
CREATE POLICY admin_retention_hold_update
  ON public.document_retention_holds FOR UPDATE TO authenticated
  USING (private.is_admin()) WITH CHECK (private.is_admin());

CREATE OR REPLACE FUNCTION private.prevent_lease_agreement_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
  RAISE EXCEPTION 'lease_agreements is append-only; create a new agreement version instead'
    USING ERRCODE = '55000';
END;
$$;

REVOKE ALL ON FUNCTION private.prevent_lease_agreement_mutation() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS lease_agreements_append_only ON public.lease_agreements;
CREATE TRIGGER lease_agreements_append_only
BEFORE UPDATE OR DELETE ON public.lease_agreements
FOR EACH ROW EXECUTE FUNCTION private.prevent_lease_agreement_mutation();

CREATE INDEX IF NOT EXISTS idx_toll_transfer_notices_customer_id
  ON public.toll_transfer_notices (customer_id);

DO $$
BEGIN
  IF to_regclass('public.customers') IS NOT NULL THEN
    ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS is_imported BOOLEAN NOT NULL DEFAULT FALSE;
    UPDATE public.customers
    SET is_imported = TRUE
    WHERE lower(COALESCE(source, '')) IN ('demo', 'imported', 'legacy', 'legacy-import', 'test')
       OR lower(COALESCE(email, '')) LIKE '%@example.invalid'
       OR COALESCE(phone, '') = '0000000000';
    CREATE INDEX IF NOT EXISTS idx_customers_current_name
      ON public.customers (full_name, id) WHERE is_imported = FALSE;
  END IF;

  IF to_regclass('public.invoices') IS NOT NULL THEN
    ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS is_imported BOOLEAN NOT NULL DEFAULT FALSE;
    UPDATE public.invoices AS invoice
    SET is_imported = TRUE
    WHERE lower(COALESCE(invoice.source, '')) IN ('demo', 'imported', 'legacy', 'legacy-import', 'test')
       OR EXISTS (
         SELECT 1 FROM public.customers AS customer
         WHERE customer.id = invoice.customer_id AND customer.is_imported
       );
    CREATE INDEX IF NOT EXISTS idx_invoices_current_date
      ON public.invoices (invoice_date DESC, id) WHERE is_imported = FALSE;
  END IF;
END $$;

-- Remove dangerous object-level privileges while retaining only the Data API
-- operations supported by the existing RLS policies.
DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'agreement_templates', 'applications', 'bookings', 'customers', 'invoices',
    'maintenance_reset_audit_events', 'manual_invoice_audit_events',
    'manual_invoice_items', 'manual_invoices', 'merchants', 'rentals', 'stripe_webhook_events',
    'toll_transfer_notice_audit_events', 'toll_transfer_notices'
  ]
  LOOP
    IF to_regclass(format('public.%I', table_name)) IS NOT NULL THEN
      EXECUTE format('REVOKE ALL ON public.%I FROM anon, authenticated', table_name);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', table_name);
      EXECUTE format('GRANT ALL ON public.%I TO service_role', table_name);
    END IF;
  END LOOP;
END $$;

REVOKE ALL ON public.lease_agreements FROM anon, authenticated;
GRANT SELECT, INSERT ON public.lease_agreements TO authenticated;
GRANT ALL ON public.lease_agreements TO service_role;

DO $$
DECLARE
  append_only_table TEXT;
BEGIN
  FOREACH append_only_table IN ARRAY ARRAY[
    'maintenance_reset_audit_events',
    'manual_invoice_audit_events',
    'stripe_webhook_events',
    'toll_transfer_notice_audit_events'
  ]
  LOOP
    IF to_regclass(format('public.%I', append_only_table)) IS NOT NULL THEN
      EXECUTE format('REVOKE ALL ON public.%I FROM authenticated', append_only_table);
      EXECUTE format('GRANT SELECT, INSERT ON public.%I TO authenticated', append_only_table);
    END IF;
  END LOOP;
END $$;

-- Public submissions are server-mediated today, but retain the existing
-- anonymous INSERT contract until the legacy policy is intentionally retired.
GRANT INSERT ON public.applications TO anon;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMIT;
