import { beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * Regression coverage for the verified payment lifecycle bridge.
 *
 * The invariant under test throughout: recording payment and creating an
 * operational rental are separate. Nothing in this file may cause a rental to
 * appear as a side effect of payment.
 */

type Row = Record<string, any>;

// The whole harness lives inside vi.hoisted because vi.mock factories are
// hoisted above module-level declarations.
const harness = vi.hoisted(() => {
  type HRow = Record<string, any>;

  const tables: Record<string, HRow[]> = {
    applications: [],
    customers: [],
    invoices: [],
    rentals: [],
  };

  /** Every write the mock database performed, for asserting side effects. */
  const writeLog: Array<{
    operation: 'insert' | 'update';
    table: string;
    payload: HRow;
  }> = [];
  const relationshipAuditEvents: HRow[] = [];

  const state: {
    beforeApplicationUpdate: (() => void) | null;
    beforeCustomerInsertFailure: (() => void) | null;
    customerInsertError: HRow | null;
    nextId: number;
    rentalInsertError: HRow | null;
    rentalIdentitySequenceLastValue: number;
    relationshipAuditError: HRow | null;
  } = {
    beforeApplicationUpdate: null,
    beforeCustomerInsertFailure: null,
    customerInsertError: null,
    nextId: 1,
    rentalInsertError: null,
    rentalIdentitySequenceLastValue: 692,
    relationshipAuditError: null,
  };

  const matchesFilters = (row: HRow, filters: Array<[string, string, any]>) =>
  filters.every(([type, column, value]) => {
    if (type === 'eq') return String(row[column] ?? '') === String(value);
    if (type === 'isNull') return row[column] === null || row[column] === undefined;
    if (type === 'in') return (value as any[]).some((entry) => String(entry) === String(row[column] ?? ''));
    if (type === 'notNull') return row[column] !== null && row[column] !== undefined;
    return true;
  });

  const createBuilder = (table: string) => {
  const filters: Array<[string, string, any]> = [];
  let mode: 'select' | 'insert' | 'update' = 'select';
  let payload: HRow = {};

  const resolveRows = () => (tables[table] || []).filter((row) => matchesFilters(row, filters));

  const applyWrite = () => {
    if (mode === 'insert') {
      if (table === 'customers' && state.customerInsertError) {
        state.beforeCustomerInsertFailure?.();
        state.beforeCustomerInsertFailure = null;
        return { error: state.customerInsertError, rows: [] };
      }
      if (table === 'rentals' && state.rentalInsertError) {
        return { error: state.rentalInsertError, rows: [] };
      }

      if (table === 'rentals') {
        const duplicateLiveRental = tables.rentals.some((rental) =>
          String(rental.status || '').trim().toLowerCase() !== 'completed' &&
          String(rental.status || '').trim().toLowerCase() !== 'cancelled' &&
          (String(rental.application_id) === String(payload.application_id) ||
            String(rental.stripe_subscription_id) === String(payload.stripe_subscription_id))
        );
        if (duplicateLiveRental) {
          return {
            error: {
              code: '23505',
              message: 'duplicate key value violates unique constraint "rentals_live_application_unique"',
            },
            rows: [],
          };
        }
      }

      // Models GENERATED BY DEFAULT AS IDENTITY: an omitted id consumes the
      // identity-owned sequence without an application-supplied value.
      const inserted = table === 'rentals'
        ? {
            bond_paid: 0,
            id: ++state.rentalIdentitySequenceLastValue,
            legacy_application_id: null,
            ...payload,
          }
        : { id: state.nextId++, ...payload };
      tables[table].push(inserted);
      writeLog.push({ operation: 'insert', payload, table });
      return { error: null, rows: [inserted] };
    }

    if (mode === 'update') {
      if (table === 'applications' && state.beforeApplicationUpdate) {
        const mutate = state.beforeApplicationUpdate;
        state.beforeApplicationUpdate = null;
        mutate();
      }
      const updated = resolveRows();
      updated.forEach((row) => Object.assign(row, payload));
      writeLog.push({ operation: 'update', payload, table });
      return { error: null, rows: updated };
    }

    return { error: null, rows: resolveRows() };
  };

  const builder: any = {
    eq(column: string, value: any) {
      filters.push(['eq', column, value]);
      return builder;
    },
    in(column: string, value: any[]) {
      filters.push(['in', column, value]);
      return builder;
    },
    is(column: string, value: any) {
      if (value === null) {
        filters.push(['isNull', column, value]);
      } else {
        filters.push(['eq', column, value]);
      }
      return builder;
    },
    not(column: string, _operator: string, _value: any) {
      filters.push(['notNull', column, null]);
      return builder;
    },
    order() {
      return builder;
    },
    select() {
      return builder;
    },
    insert(nextPayload: HRow) {
      mode = 'insert';
      payload = nextPayload;
      return builder;
    },
    update(nextPayload: HRow) {
      mode = 'update';
      payload = nextPayload;
      return builder;
    },
    async maybeSingle() {
      const { error, rows } = applyWrite();
      return { data: rows[0] ?? null, error };
    },
    async single() {
      const { error, rows } = applyWrite();
      if (error) {
        return { data: null, error };
      }
      if (rows.length !== 1) {
        return { data: null, error: { message: 'Expected exactly one row' } };
      }
      return { data: rows[0], error: null };
    },
    then(resolve: (value: any) => unknown) {
      const { error, rows } = applyWrite();
      return Promise.resolve(resolve({ data: rows, error }));
    },
  };

  return builder;
  };

  const persistRelationshipRpc = async (params: HRow) => {
    const tableSnapshot = structuredClone(tables);
    const writeLogLength = writeLog.length;
    const auditLength = relationshipAuditEvents.length;
    const rollback = (message: string) => {
      Object.keys(tables).forEach((table) => {
        tables[table] = tableSnapshot[table] || [];
      });
      writeLog.length = writeLogLength;
      relationshipAuditEvents.length = auditLength;
      return { data: null, error: { message } };
    };

    state.beforeApplicationUpdate?.();
    state.beforeApplicationUpdate = null;

    const application = tables.applications.find(
      (row) => String(row.id) === String(params.p_application_id)
    );
    if (!application) return rollback('maple_error:application_missing');
    if (application.status === 'Cancelled') return rollback('maple_error:application_cancelled');
    if (Number(application.payment_link_version || 0) !== Number(params.p_payment_link_version)) {
      return rollback('maple_error:payment_link_version_mismatch');
    }
    if (application.stripe_customer_id && application.stripe_customer_id !== params.p_stripe_customer_id) {
      return rollback('maple_error:customer_identity_conflict');
    }
    if (application.stripe_subscription_id && application.stripe_subscription_id !== params.p_stripe_subscription_id) {
      return rollback('maple_error:subscription_identity_conflict');
    }
    if (params.p_checkout_session_id && application.stripe_checkout_session_id && application.stripe_checkout_session_id !== params.p_checkout_session_id) {
      return rollback('maple_error:checkout_session_identity_conflict');
    }

    Object.assign(application, {
      ...(params.p_checkout_session_id
        ? { stripe_checkout_session_id: params.p_checkout_session_id }
        : {}),
      stripe_customer_id: params.p_stripe_customer_id,
      stripe_subscription_id: params.p_stripe_subscription_id,
    });
    writeLog.push({ operation: 'update', payload: params, table: 'applications' });

    if (application.status !== 'Paid') {
      return { data: { customerId: null, operation: 'unchanged' }, error: null };
    }

    const byApplication = tables.customers.find(
      (row) => String(row.application_id || '') === String(application.id)
    );
    const byStripe = tables.customers.find(
      (row) => String(row.stripe_customer_id || '') === String(params.p_stripe_customer_id)
    );
    if (byApplication && byStripe && Number(byApplication.id) !== Number(byStripe.id)) {
      return rollback('maple_error:customer_identity_ambiguous');
    }
    if (byApplication?.stripe_customer_id && byApplication.stripe_customer_id !== params.p_stripe_customer_id) {
      return rollback('maple_error:customer_identity_ambiguous');
    }
    if (byStripe?.application_id && String(byStripe.application_id) !== String(application.id)) {
      return rollback('maple_error:customer_identity_ambiguous');
    }

    let customer = byApplication || byStripe;
    let operation = 'unchanged';
    if (customer) {
      operation = String(customer.application_id || '') === String(application.id) &&
        String(customer.stripe_customer_id || '') === String(params.p_stripe_customer_id)
        ? 'unchanged'
        : 'link';
      Object.assign(customer, {
        application_id: application.id,
        email: application.email || null,
        full_name: String(application.name || '').trim() || 'Maple Rentals customer',
        phone: application.phone || null,
        street: application.address || null,
        stripe_customer_id: params.p_stripe_customer_id,
      });
      writeLog.push({ operation: 'update', payload: customer, table: 'customers' });
    } else if (state.customerInsertError) {
      state.beforeCustomerInsertFailure?.();
      state.beforeCustomerInsertFailure = null;
      customer = tables.customers.find(
        (row) => String(row.stripe_customer_id || '') === String(params.p_stripe_customer_id)
      );
      if (!customer || String(customer.application_id || '') !== String(application.id)) {
        const concurrentCustomer = customer ? structuredClone(customer) : null;
        const rolledBack = rollback('maple_error:customer_identity_ambiguous');
        if (concurrentCustomer) tables.customers.push(concurrentCustomer);
        return rolledBack;
      }
    } else {
      customer = {
        application_id: application.id,
        email: application.email || null,
        external_id: `stripe:${params.p_stripe_customer_id}`,
        full_name: String(application.name || '').trim() || 'Maple Rentals customer',
        id: state.nextId++,
        phone: application.phone || null,
        source: 'stripe-verified',
        street: application.address || null,
        stripe_customer_id: params.p_stripe_customer_id,
      };
      tables.customers.push(customer);
      writeLog.push({ operation: 'insert', payload: customer, table: 'customers' });
      operation = 'create';
    }

    if (operation !== 'unchanged') {
      if (state.relationshipAuditError) {
        return rollback(String(state.relationshipAuditError.message || 'audit insert failed'));
      }
      relationshipAuditEvents.push({
        action: operation === 'create'
          ? 'operational_customer_created'
          : 'operational_customer_linked',
        actor: null,
        metadata: {
          applicationId: application.id,
          customerId: customer.id,
          operation,
          paymentLinkVersion: Number(params.p_payment_link_version),
          source: 'verified-stripe-payment',
        },
        targetId: application.id,
        targetType: 'application',
      });
    }

    return { data: { customerId: customer.id, operation }, error: null };
  };

  const reset = () => {
    Object.keys(tables).forEach((table) => {
      tables[table] = [];
    });
    writeLog.length = 0;
    state.nextId = 1;
    state.beforeApplicationUpdate = null;
    state.beforeCustomerInsertFailure = null;
    state.customerInsertError = null;
    state.rentalInsertError = null;
    state.rentalIdentitySequenceLastValue = 692;
    state.relationshipAuditError = null;
    relationshipAuditEvents.length = 0;
  };

  return {
    mockDb: {
      from: (table: string) => createBuilder(table),
      rpc: (name: string, params: HRow) => name === 'persist_verified_stripe_relationship'
        ? persistRelationshipRpc(params)
        : Promise.resolve({ data: null, error: null }),
    },
    relationshipAuditEvents,
    reset,
    state,
    tables,
    writeLog,
  };
});

const { relationshipAuditEvents, state, tables, writeLog } = harness;

const mockSubscriptionsRetrieve = vi.hoisted(() => vi.fn());
const mockRecordAdminAuditEvent = vi.hoisted(() => vi.fn());

vi.mock('./db/index.js', () => ({ db: harness.mockDb }));

vi.mock('./db/postgres.js', () => ({
  hasDirectDatabaseConnection: () => false,
  withPostgresAdvisoryLock: async (_key: string, callback: () => Promise<unknown>) =>
    callback(),
  withPostgresTransaction: vi.fn(),
}));

vi.mock('./schemaCompat.js', () => ({
  getRentalApplicationIdColumn: async () => 'application_id',
  getSchemaCompat: async () => ({
    applicationApprovedVehicleColumn: 'approved_vehicle',
    applicationApprovedWeeklyPriceColumn: 'approved_weekly_price',
    applicationIntendedStartDateColumn: 'intended_start_date',
    applicationPaidAtColumn: 'paid_at',
    applicationPaymentLinkVersionColumn: 'payment_link_version',
    coreMode: 'snake',
    rentalStripeCustomerColumn: 'stripe_customer_id',
    rentalStripeSubscriptionColumn: 'stripe_subscription_id',
  }),
}));

vi.mock('./stripeClient.js', () => ({
  getStripeClient: () => ({
    subscriptions: { retrieve: mockSubscriptionsRetrieve },
  }),
}));

vi.mock('./adminAudit.js', () => ({
  recordAdminAuditEvent: mockRecordAdminAuditEvent,
}));

import {
  ACTIVATION_ELIGIBLE_SUBSCRIPTION_STATUSES,
  activateRentalForApplication,
  getRentalActivationErrorLog,
  listPendingRentalActivations,
  PaymentLifecycleError,
  RentalActivationPersistenceError,
  persistCheckoutRelationshipFromSession,
  persistVerifiedStripeRelationship,
} from './paymentLifecycle.js';

const APPLICATION_ID = '11111111-1111-4111-8111-111111111111';
const OTHER_APPLICATION_ID = '22222222-2222-4222-8222-222222222222';
const CUSTOMER_ID = 'cus_verified';
const SUBSCRIPTION_ID = 'sub_verified';

const seedPaidApplication = (overrides: Row = {}) => {
  const application = {
    address: '1 Test Street',
    approved_vehicle: 'ABC123',
    approved_weekly_price: 350,
    email: 'driver@example.com',
    id: APPLICATION_ID,
    intended_start_date: '2026-09-01',
    legacy_id: null,
    name: 'Test Driver',
    paid_at: '2026-08-16T00:00:00.000Z',
    payment_link_version: 2,
    phone: '0400000000',
    status: 'Paid',
    stripe_checkout_session_id: null,
    stripe_customer_id: null,
    stripe_subscription_id: null,
    ...overrides,
  };
  tables.applications.push(application);
  return application;
};

const verifiedRelationship = (overrides: Row = {}) => ({
  applicationId: APPLICATION_ID,
  checkoutSessionId: 'cs_verified',
  customerId: CUSTOMER_ID,
  paymentLinkVersion: 2,
  subscriptionId: SUBSCRIPTION_ID,
  ...overrides,
});

const activeSubscription = (overrides: Row = {}) => ({
  customer: CUSTOMER_ID,
  id: SUBSCRIPTION_ID,
  metadata: { application_id: APPLICATION_ID },
  status: 'active',
  ...overrides,
});

beforeEach(() => {
  harness.reset();
  mockSubscriptionsRetrieve.mockReset();
  mockRecordAdminAuditEvent.mockReset();
});

describe('persistVerifiedStripeRelationship', () => {
  it('links exactly one operational customer for a verified paid application', async () => {
    seedPaidApplication();

    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.customers).toHaveLength(1);
    expect(tables.customers[0]).toMatchObject({
      application_id: APPLICATION_ID,
      stripe_customer_id: CUSTOMER_ID,
    });
    expect(tables.applications[0]).toMatchObject({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
  });

  it('never creates a rental as a side effect of recording payment identity', async () => {
    seedPaidApplication();

    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.rentals).toHaveLength(0);
    expect(writeLog.some((entry) => entry.table === 'rentals')).toBe(false);
  });

  it('is idempotent across webhook replay and creates no duplicate customer', async () => {
    seedPaidApplication();

    await persistVerifiedStripeRelationship(verifiedRelationship());
    await persistVerifiedStripeRelationship(verifiedRelationship());
    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.customers).toHaveLength(1);
  });

  it('links an existing application customer instead of inserting a second one', async () => {
    seedPaidApplication();
    tables.customers.push({
      application_id: APPLICATION_ID,
      full_name: 'Test Driver',
      id: 99,
      stripe_customer_id: null,
    });

    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.customers).toHaveLength(1);
    expect(tables.customers[0]).toMatchObject({
      id: 99,
      stripe_customer_id: CUSTOMER_ID,
    });
  });

  it('does not merge a same-named customer that has no durable link', async () => {
    seedPaidApplication();
    tables.customers.push({
      application_id: null,
      full_name: 'Test Driver',
      id: 77,
      stripe_customer_id: null,
    });

    await persistVerifiedStripeRelationship(verifiedRelationship());

    // The identically named record is untouched; matching is never by name.
    expect(tables.customers).toHaveLength(2);
    expect(tables.customers.find((row) => row.id === 77)).toMatchObject({
      application_id: null,
      stripe_customer_id: null,
    });
  });

  it('rejects a stale payment link version rather than linking incorrectly', async () => {
    seedPaidApplication({ payment_link_version: 3 });

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship({ paymentLinkVersion: 2 }))
    ).rejects.toMatchObject({ code: 'payment_link_version_mismatch' });

    expect(tables.customers).toHaveLength(0);
  });

  it('refuses to relink an application that already holds another subscription', async () => {
    seedPaidApplication({ stripe_subscription_id: 'sub_other' });

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'subscription_identity_conflict' });
  });

  it('refuses to relink an application that already holds another Stripe customer', async () => {
    seedPaidApplication({ stripe_customer_id: 'cus_other' });

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'customer_identity_conflict' });

    expect(writeLog).toHaveLength(0);
  });

  it('refuses to overwrite a different stored Checkout session', async () => {
    seedPaidApplication({ stripe_checkout_session_id: 'cs_other' });

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'checkout_session_identity_conflict' });

    expect(writeLog).toHaveLength(0);
  });

  it.each([
    ['cancellation', { status: 'Cancelled' }, 'application_cancelled'],
    ['payment-link regeneration', { payment_link_version: 3 }, 'payment_link_version_mismatch'],
    ['a competing subscription', { stripe_subscription_id: 'sub_competing' }, 'subscription_identity_conflict'],
    ['a competing Stripe customer', { stripe_customer_id: 'cus_competing' }, 'customer_identity_conflict'],
    ['a competing Checkout session', { stripe_checkout_session_id: 'cs_competing' }, 'checkout_session_identity_conflict'],
  ])('does not overwrite %s that lands between validation and persistence', async (_case, change, expectedCode) => {
    const application = seedPaidApplication();
    state.beforeApplicationUpdate = () => Object.assign(application, change);

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: expectedCode });

    expect(tables.customers).toHaveLength(0);
    expect(application).toMatchObject(change);
    expect(application.stripe_subscription_id).not.toBe(SUBSCRIPTION_ID);
  });

  it('rejects a conflicting customer that wins the insert race', async () => {
    seedPaidApplication();
    state.customerInsertError = { code: '23505', message: 'duplicate customer identity' };
    state.beforeCustomerInsertFailure = () => {
      tables.customers.push({
        application_id: OTHER_APPLICATION_ID,
        id: 88,
        stripe_customer_id: CUSTOMER_ID,
      });
    };

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'customer_identity_ambiguous' });

    expect(tables.customers).toHaveLength(1);
    expect(tables.customers[0].application_id).toBe(OTHER_APPLICATION_ID);
    expect(tables.applications[0]).toMatchObject({
      stripe_checkout_session_id: null,
      stripe_customer_id: null,
      stripe_subscription_id: null,
    });
  });

  it('rolls back application and customer identity when the audit insert fails', async () => {
    seedPaidApplication();
    state.relationshipAuditError = { message: 'audit insert failed' };

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toThrow('Failed to atomically persist');

    expect(tables.applications[0]).toMatchObject({
      stripe_checkout_session_id: null,
      stripe_customer_id: null,
      stripe_subscription_id: null,
    });
    expect(tables.customers).toHaveLength(0);
    expect(relationshipAuditEvents).toHaveLength(0);
  });

  it('escalates a Stripe customer already owned by another application', async () => {
    seedPaidApplication();
    tables.customers.push({
      application_id: OTHER_APPLICATION_ID,
      full_name: 'Someone Else',
      id: 55,
      stripe_customer_id: CUSTOMER_ID,
    });

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'customer_identity_ambiguous' });
  });

  it('does not make a cancelled application an operational customer', async () => {
    seedPaidApplication({ status: 'Cancelled' });

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'application_cancelled' });

    expect(tables.customers).toHaveLength(0);
  });

  it('does not create an operational customer for an Approved application that is not yet Paid', async () => {
    seedPaidApplication({ status: 'Approved' });

    const result = await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(result).toEqual({ customerId: null });
    expect(tables.customers).toHaveLength(0);
    expect(writeLog.some((entry) => entry.table === 'customers')).toBe(false);
  });

  it('still records verified Stripe identity for a not-yet-Paid application', async () => {
    seedPaidApplication({ status: 'Approved' });

    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.applications[0]).toMatchObject({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
  });

  it('creates no operational customer for any non-Paid application status', async () => {
    for (const status of ['Approved', 'Payment Review', 'Rejected']) {
      harness.reset();
      seedPaidApplication({ status });

      const result = await persistVerifiedStripeRelationship(verifiedRelationship());

      expect(result).toEqual({ customerId: null });
      expect(tables.customers).toHaveLength(0);
    }
  });

  it('never creates a rental for a not-yet-Paid application carrying Stripe identity', async () => {
    seedPaidApplication({ status: 'Approved' });

    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.rentals).toHaveLength(0);
    expect(writeLog.some((entry) => entry.table === 'rentals')).toBe(false);
  });
});

describe('operational customer audit trail', () => {
  /** Metadata keys that would leak credentials, PII, or payment data. */
  const FORBIDDEN_METADATA_KEYS = [
    'address',
    'cardBrand',
    'email',
    'last4',
    'name',
    'paymentMethod',
    'phone',
    'stripeCustomerId',
    'stripeSecretKey',
    'stripeSubscriptionId',
    'supabaseKey',
    'supabaseServiceRoleKey',
  ];

  it('audits the operational customer create for a paid, eligible reconciliation', async () => {
    seedPaidApplication();

    const result = await persistVerifiedStripeRelationship(verifiedRelationship());

    // The trusted relationship is persisted...
    expect(tables.applications[0]).toMatchObject({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    expect(tables.customers).toHaveLength(1);

    // ...and the operational customer mutation is audited exactly once.
    expect(relationshipAuditEvents).toHaveLength(1);
    expect(relationshipAuditEvents[0]).toEqual({
      action: 'operational_customer_created',
      actor: null,
      metadata: {
        applicationId: APPLICATION_ID,
        customerId: result.customerId,
        operation: 'create',
        paymentLinkVersion: 2,
        source: 'verified-stripe-payment',
      },
      targetId: APPLICATION_ID,
      targetType: 'application',
    });
  });

  it('audits a link when an existing operational customer is attached instead of created', async () => {
    seedPaidApplication();
    tables.customers.push({
      application_id: APPLICATION_ID,
      full_name: 'Test Driver',
      id: 99,
      stripe_customer_id: null,
    });

    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.customers).toHaveLength(1);
    expect(relationshipAuditEvents).toHaveLength(1);
    expect(relationshipAuditEvents[0]).toMatchObject({
      action: 'operational_customer_linked',
      metadata: { customerId: 99, operation: 'link' },
    });
  });

  it('records no credentials, payment data, or applicant contact details', async () => {
    seedPaidApplication();

    await persistVerifiedStripeRelationship(verifiedRelationship());

    const { metadata } = relationshipAuditEvents[0];
    FORBIDDEN_METADATA_KEYS.forEach((key) => {
      expect(metadata).not.toHaveProperty(key);
    });
    const serialized = JSON.stringify(metadata);
    expect(serialized).not.toContain('driver@example.com');
    expect(serialized).not.toContain('0400000000');
    expect(serialized).not.toContain('1 Test Street');
    expect(serialized).not.toContain('sk_');
  });

  it('performs no write and no audit mutation for a cancelled application', async () => {
    seedPaidApplication({ status: 'Cancelled' });

    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'application_cancelled' });

    expect(writeLog).toHaveLength(0);
    expect(tables.customers).toHaveLength(0);
    expect(relationshipAuditEvents).toHaveLength(0);
  });

  it.each(['canceled', 'past_due', 'unpaid', 'incomplete', 'incomplete_expired', 'paused'])(
    'writes and audits nothing for a subscription in %s state',
    async (subscriptionStatus) => {
      seedPaidApplication();

      // Mirrors the reconciliation gate: an unsafe subscription state is never
      // writable, so persistence is never reached. Using the real exported
      // allow-list means widening it would fail this test.
      const writable = ACTIVATION_ELIGIBLE_SUBSCRIPTION_STATUSES.has(subscriptionStatus);
      expect(writable).toBe(false);
      if (writable) {
        await persistVerifiedStripeRelationship(verifiedRelationship());
      }

      expect(writeLog).toHaveLength(0);
      expect(tables.customers).toHaveLength(0);
      expect(relationshipAuditEvents).toHaveLength(0);
    }
  );

  it('performs no write and no audit mutation when the application is missing', async () => {
    await expect(
      persistVerifiedStripeRelationship(verifiedRelationship())
    ).rejects.toMatchObject({ code: 'application_missing' });

    expect(writeLog).toHaveLength(0);
    expect(tables.customers).toHaveLength(0);
    expect(relationshipAuditEvents).toHaveLength(0);
  });

  it('does not audit a duplicate mutation on webhook or reconciliation replay', async () => {
    seedPaidApplication();

    await persistVerifiedStripeRelationship(verifiedRelationship());
    await persistVerifiedStripeRelationship(verifiedRelationship());
    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(tables.customers).toHaveLength(1);
    expect(relationshipAuditEvents).toHaveLength(1);
    expect(relationshipAuditEvents[0]).toMatchObject({
      action: 'operational_customer_created',
    });
  });

  it('does not audit an already-linked operational customer', async () => {
    seedPaidApplication();
    tables.customers.push({
      application_id: APPLICATION_ID,
      full_name: 'Test Driver',
      id: 42,
      stripe_customer_id: CUSTOMER_ID,
    });

    const result = await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(result).toEqual({ customerId: 42 });
    expect(tables.customers).toHaveLength(1);
    expect(relationshipAuditEvents).toHaveLength(0);
  });

  it('never audits an operational customer for a not-yet-Paid application', async () => {
    seedPaidApplication({ status: 'Approved' });

    await persistVerifiedStripeRelationship(verifiedRelationship());

    expect(relationshipAuditEvents).toHaveLength(0);
  });

  it('creates no rental and touches no fleet state while auditing the link', async () => {
    seedPaidApplication();

    await persistVerifiedStripeRelationship(verifiedRelationship());

    const touchedTables = new Set(writeLog.map((entry) => entry.table));
    expect(touchedTables.has('rentals')).toBe(false);
    expect(touchedTables.has('cars')).toBe(false);
    expect(touchedTables.has('fleet_imports')).toBe(false);
    expect(tables.rentals).toHaveLength(0);
    // Reconciliation records identity only; application status is untouched.
    expect(tables.applications[0].status).toBe('Paid');
  });
});

describe('persistCheckoutRelationshipFromSession', () => {
  it('ignores a session that is not a Maple vehicle checkout', async () => {
    seedPaidApplication();

    const result = await persistCheckoutRelationshipFromSession({
      customer: CUSTOMER_ID,
      id: 'cs_other',
      metadata: { application_id: APPLICATION_ID, checkout_kind: 'other', payment_link_version: '2' },
      subscription: SUBSCRIPTION_ID,
    } as never);

    expect(result).toBeNull();
    expect(tables.customers).toHaveLength(0);
  });

  it('ignores a session with no subscription rather than guessing identity', async () => {
    seedPaidApplication();

    const result = await persistCheckoutRelationshipFromSession({
      customer: CUSTOMER_ID,
      id: 'cs_no_sub',
      metadata: { application_id: APPLICATION_ID, checkout_kind: 'vehicle', payment_link_version: '2' },
      subscription: null,
    } as never);

    expect(result).toBeNull();
    expect(tables.customers).toHaveLength(0);
  });
});

describe('listPendingRentalActivations', () => {
  it('returns paid verified subscriptions with no rental identifier attached', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });

    const pending = await listPendingRentalActivations();

    expect(pending).toHaveLength(1);
    expect(pending[0]).toMatchObject({
      application_id: APPLICATION_ID,
      approved_vehicle: 'ABC123',
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    // No rentals.id exists, so rental-only actions are not representable.
    expect(pending[0]).not.toHaveProperty('id');
  });

  it('excludes an application that already has a live rental', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    tables.rentals.push({ application_id: APPLICATION_ID, id: 1, status: 'Active' });

    await expect(listPendingRentalActivations()).resolves.toHaveLength(0);
  });

  it('still lists an application whose only rental is historical', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    tables.rentals.push({ application_id: APPLICATION_ID, id: 1, status: 'Cancelled' });

    await expect(listPendingRentalActivations()).resolves.toHaveLength(1);
  });
});

describe('activateRentalForApplication', () => {
  it('creates exactly one rental from server-derived approved values', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    const result = await activateRentalForApplication(APPLICATION_ID, 'admin@example.com');

    expect(result.created).toBe(true);
    expect(tables.rentals).toHaveLength(1);
    expect(tables.rentals[0]).toMatchObject({
      application_id: APPLICATION_ID,
      bond_paid: 0,
      customer_id: 1,
      id: 693,
      legacy_application_id: null,
      start_date: '2026-09-01',
      status: 'Active',
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
      vehicle_registration: 'ABC123',
      weekly_price: 350,
    });
    const rentalInsert = writeLog.find(
      (entry) => entry.operation === 'insert' && entry.table === 'rentals'
    );
    expect(rentalInsert?.payload).not.toHaveProperty('id');
    expect(rentalInsert?.payload).not.toHaveProperty('legacy_application_id');
    expect(mockRecordAdminAuditEvent).toHaveBeenCalledTimes(1);
  });

  it('omits bond_paid so the existing database default supplies zero', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    await activateRentalForApplication(APPLICATION_ID, 'admin@example.com');

    const rentalInsert = writeLog.find(
      (entry) => entry.operation === 'insert' && entry.table === 'rentals'
    );
    expect(rentalInsert?.payload).not.toHaveProperty('bond_paid');
    expect(tables.rentals[0].bond_paid).toBe(0);
  });

  it('is idempotent when activated twice', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    const first = await activateRentalForApplication(APPLICATION_ID, 'admin@example.com');
    const second = await activateRentalForApplication(APPLICATION_ID, 'admin@example.com');

    expect(first.created).toBe(true);
    expect(second.created).toBe(false);
    expect(tables.rentals).toHaveLength(1);
    expect(mockRecordAdminAuditEvent).toHaveBeenCalledTimes(1);
  });

  it('uses the database uniqueness guard for concurrent activation', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    tables.customers.push({
      application_id: APPLICATION_ID,
      id: 91,
      stripe_customer_id: CUSTOMER_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    const results = await Promise.all([
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com'),
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com'),
    ]);

    expect(results.map((result) => result.created).sort()).toEqual([false, true]);
    expect(tables.rentals).toHaveLength(1);
    expect(results[0].rental.id).toBe(results[1].rental.id);
    expect(mockRecordAdminAuditEvent).toHaveBeenCalledTimes(1);
  });

  it('activates despite a historical cancelled rental instead of returning it', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    tables.rentals.push({
      application_id: APPLICATION_ID,
      id: 900,
      legacy_application_id: 101,
      status: 'Cancelled',
      stripe_subscription_id: 'sub_old',
    });
    state.rentalIdentitySequenceLastValue = 900;
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    const result = await activateRentalForApplication(APPLICATION_ID, 'admin@example.com');

    expect(result.created).toBe(true);
    expect(result.rental.id).toBe(901);
    expect(tables.rentals).toHaveLength(2);
    expect(tables.rentals[0]).toMatchObject({
      id: 900,
      legacy_application_id: 101,
      stripe_subscription_id: 'sub_old',
    });
    expect(tables.rentals[1].legacy_application_id).toBeNull();
  });

  it('exposes only sanitized database diagnostics for an unexpected insert failure', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());
    state.rentalInsertError = {
      code: '23502',
      details: 'Failing row contains driver@example.com and secret customer data',
      message: 'null value in column "id" of relation "rentals" violates not-null constraint',
    };

    const error = await activateRentalForApplication(
      APPLICATION_ID,
      'admin@example.com'
    ).catch((caught) => caught);

    expect(error).toBeInstanceOf(RentalActivationPersistenceError);
    expect(getRentalActivationErrorLog(error)).toEqual({
      databaseCode: '23502',
      databaseMessage:
        'null value in column "id" of relation "rentals" violates not-null constraint',
      errorName: 'RentalActivationPersistenceError',
    });
    expect(JSON.stringify(getRentalActivationErrorLog(error))).not.toContain('secret customer data');

    const customErrorLog = getRentalActivationErrorLog(
      new RentalActivationPersistenceError({
        code: 'P0001',
        message: `Driver Name at 1 Private Street has customer ${CUSTOMER_ID}`,
      })
    );
    expect(customErrorLog).toMatchObject({
      databaseCode: 'P0001',
      databaseMessage: 'Database insert failed.',
    });
    expect(JSON.stringify(customErrorLog)).not.toContain('Driver Name');
  });

  it('rejects an application that is not Paid', async () => {
    seedPaidApplication({
      status: 'Approved',
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'application_not_paid' });

    expect(tables.rentals).toHaveLength(0);
  });

  it('rejects activation when no verified Stripe identity is linked', async () => {
    seedPaidApplication();

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'stripe_identity_missing' });

    expect(mockSubscriptionsRetrieve).not.toHaveBeenCalled();
  });

  it.each(['past_due', 'unpaid', 'incomplete', 'incomplete_expired', 'canceled', 'paused'])(
    'refuses to activate a subscription in %s state',
    async (status) => {
      seedPaidApplication({
        stripe_customer_id: CUSTOMER_ID,
        stripe_subscription_id: SUBSCRIPTION_ID,
      });
      mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription({ status }));

      await expect(
        activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
      ).rejects.toMatchObject({ code: 'subscription_not_activatable' });

      expect(tables.rentals).toHaveLength(0);
    }
  );

  it('rejects a subscription owned by a different Stripe customer', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(
      activeSubscription({ customer: 'cus_someone_else' })
    );

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'stripe_identity_mismatch' });
  });

  it('rejects a subscription whose metadata names another application', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(
      activeSubscription({ metadata: { application_id: OTHER_APPLICATION_ID } })
    );

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'stripe_identity_mismatch' });
  });

  it('refuses to invent a start date when the approved one is invalid', async () => {
    seedPaidApplication({
      intended_start_date: null,
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'start_date_invalid' });

    expect(tables.rentals).toHaveLength(0);
  });

  it('rejects an application with no approved weekly price', async () => {
    seedPaidApplication({
      approved_weekly_price: 0,
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'approved_price_invalid' });
  });

  it('rejects an application with no approved vehicle registration', async () => {
    seedPaidApplication({
      approved_vehicle: '   ',
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'approved_vehicle_missing' });
  });

  it('never mutates fleet or vehicle state during activation', async () => {
    seedPaidApplication({
      stripe_customer_id: CUSTOMER_ID,
      stripe_subscription_id: SUBSCRIPTION_ID,
    });
    mockSubscriptionsRetrieve.mockResolvedValue(activeSubscription());

    await activateRentalForApplication(APPLICATION_ID, 'admin@example.com');

    const touchedTables = new Set(writeLog.map((entry) => entry.table));
    expect(touchedTables.has('cars')).toBe(false);
    expect(touchedTables.has('fleet_imports')).toBe(false);
    // The rental carries approved registration text, never a vehicle id.
    expect(tables.rentals[0]).not.toHaveProperty('car_id');
  });

  it('surfaces a missing application as a 404 lifecycle error', async () => {
    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toMatchObject({ code: 'application_missing', status: 404 });
  });

  it('reports lifecycle failures as PaymentLifecycleError', async () => {
    seedPaidApplication({ status: 'Approved' });

    await expect(
      activateRentalForApplication(APPLICATION_ID, 'admin@example.com')
    ).rejects.toBeInstanceOf(PaymentLifecycleError);
  });
});
